[build]
  publish = "packages/node_modules/samples"
  command = "npm run samples:build --env=production"
[context.production.environment]
  NODE_ENV = "development"
[context.deploy-preview.environment]
  NODE_ENV = "development"
[context.branch-deploy]
  NODE_ENV = "development"
